### ISSUE TITLE
Add a Testnet property

### ISSUE THREAD

**Issue by fmrsabino** [safe-global/safe-config-service#1022]
A testnet property should be added to each chain so that clients can correctly distinguish between two categories: Non-testnets and testnets.

#### Proposed API

Add `isTestnet` flag to [`Chain` model](https://github.com/safe-global/safe-config-service/blob/main/src/chains/models.py#L57)

**Comment by iamacook** [comment]
@safe-global/safe-web, please confirm whether the proposed API is sufficient. I suggest the same for the gateway.

**Comment by katspaugh** [comment]
Yes, looks good. 👍
