### ISSUE TITLE
`/api/v1/chains` returns unexpected nativeCurrency.logoUri path

### ISSUE THREAD

**Issue by gugugu47** [safe-global/safe-config-service#1086]
**Describe the bug**
I deployed a project locally using the code from `https://github.com/safe-global/safe-infrastructure`. However, after adding a configuration for a chain in cfg, the `/v1/chains` endpoint of cgw started returning a 500 error. After enabling debug logs, I found that cgw returned the following error:
```json
{
    "build_number": "edc276d",
    "level": "error",
    "message": {
        "chain_id": null,
        "client_ip": "172.70.223.68",
        "detail": "[\n  {\n    \"validation\": \"url\",\n    \"code\": \"invalid_string\",\n    \"message\": \"Invalid url\",\n    \"path\": [\n      \"nativeCurrency\",\n      \"logoUri\"\n    ]\n  }\n]",
        "method": "GET",
        "path": "/v1/chains",
        "response_time_ms": 107.19920100085437,
        "route": "/v1/chains",
        "safe_app_user_agent": null,
        "status_code": 500
    },
    "request_id": "1e37d27b-02b6-468a-a290-b6e06f7bc911",
    "timestamp": "2024-03-29T07:54:29.220Z",
    "version": "v1.31.0"
}
````
After investigating further, I found that the `nativeCurrency.logoUri` in the response data from cfg is not an absolute path:

```json
{
    "count": 1,
    "next": null,
    "previous": null,
    "results": [
        {
          ...
            "nativeCurrency": {
                "name": "ETH",
                "symbol": "ETH",
                "decimals": 18,
                "logoUri": "/media/chains/100/currency_logo_3fdtfcf.png"
            },
          ...
    ]
}
```

**To Reproduce**

 - Clone the code from `https://github.com/safe-global/safe-infrastructure`
 - Modify the MEDIA_URL in cfg.env to `/media/`
**Expected behavior**
The `nativeCurrency.logoUri` in the response data from cfg should be `https://config.xxx.xyz/media/chains/100/currency_logo_3fdtfcf.png` instead of `/media/chains/100/currency_logo_3fdtfcf.png`.

**Environment (please complete the following information):**
 - Version of safe-config-service: latest(possibly [v2.75.0])
 
**Additional context**
I made the following edits to the `src/chains/serializers.py` file
from
```python
    @staticmethod
    @swagger_serializer_method(serializer_or_field=CurrencySerializer)  # type: ignore[misc]
    def get_native_currency(obj: Chain) -> ReturnDict:
        return CurrencySerializer(obj).data
```
to
```python
    @swagger_serializer_method(serializer_or_field=CurrencySerializer)  # type: ignore[misc]
    def get_native_currency(self, obj: Chain) -> ReturnDict:
        request = self.context.get('request')
        logo_uri = obj.currency_logo_uri
        dict = CurrencySerializer(obj).data
        dict.update({"logo_uri":request.build_absolute_uri(logo_uri)})
        return dict
```
After applying the temporary workaround, cfg is able to return the expected data. However, since I'm not familiar with Python and Django, this was just a temporary solution on my part. I hope that you can find a better way to fix this issue.

**Comment by abhinavmsra** [comment]
Hi @gugugu47 I ran into a similar issue. If you set `MEDIA_URL` env, it seems to resolve the issue
