### ISSUE TITLE
Error running docker compose web

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-config-service#553]
**Describe the bug**
When I run ``` docker compose up ``` I get an error with the following message:
```
safe-config-service-web-1    | django.core.exceptions.ImproperlyConfigured: Storage set to S3 but AWS is not configured
```

**To Reproduce**
- Copy the environment ``` cp .env.example .env ```
- Run docker ``` docker compose up ```

**Expected behavior**
Run the service without need a S3 storage. 

**Environment (please complete the following information):**
 - Dev
 - OS: Linux 5.15.32-1-MANJARO
 - Version: last commit in main branch

**Comment by Uxio0** [comment]
@moisses89 For fixing this take a look into the configuration for https://github.com/safe-global/safe-infrastructure
