### ISSUE TITLE
Is there any documentation available?

### ISSUE THREAD

**Issue by stebansaa** [safe-global/safe-config-service#563]
Trying to find some information on how to configure things so that they work with Safe client Gateway. Thank you!

**Comment by fmrsabino** [comment]
Hey @stebansaa

This repository is constrained to how to setup the `safe-config-service`.

We have a different repo that goes over how to setup the Safe Client Gateway, Safe Config Service and Safe Transaction Service: https://github.com/safe-global/safe-infrastructure

Hopefully this helps in setting up the different services.
