### ISSUE TITLE
"Schemes=http" when domain name configured

### ISSUE THREAD

**Issue by masayil** [safe-global/safe-config-service#634]
https://gnosis-config-dev.ankr.com/
I configured the domain name but it still shows http.
![image](https://user-images.githubusercontent.com/65291464/184627528-da1efc47-692e-48f7-a873-c81d8aa7362c.png)

**Comment by masayil** [comment]
![image](https://user-images.githubusercontent.com/65291464/184627563-0bc9bef6-3867-41b0-a30c-27cb4672f7e2.png)
Setting `proxy_set_header X-Forwarded-Proto $scheme;` can reslove it.
I am not sure that which one is correct.

**Comment by masayil** [comment]
upstream app_server {
    server 127.0.0.1:8000 fail_timeout=0;
    keepalive 32;
  }

server {
        listen    0.0.0.0:80;
        server_name   gnosis-config-dev.ankr.com;
        rewrite ^(.*) https://$server_name$1 permanent;
}

server {
        listen    0.0.0.0:443 ssl;
        server_name   gnosis-config-dev.ankr.com;
        ssl_certificate     /etc/nginx/cert/_.ankr.com.crt;
        ssl_certificate_key  /etc/nginx/cert/_.ankr.com.key;
        ssl_session_timeout  5m;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        client_max_body_size 10M;
        access_log /var/log/nginx/gnosis-config-dev.ankr.com.access.log access;
        error_log /var/log/nginx/gnosis-config-dev.ankr.com.error.log ;
        charset utf-8;
        gzip    on;
        gzip_min_length 10000;
        gzip_comp_level  2;
          # text/html is always included by default
    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/javascript text/xml application/xml application/rss+xml application/atom+xml application/rdf+xml;
    gzip_disable "MSIE [1-6]\.";

    # allow the server to close connection on non responding client, this will free up memory
    reset_timedout_connection on;
    # Redirect http to https
    if ($http_x_forwarded_proto = 'http') {
      return 301 https://$host$request_uri;
    }



        location /static {
            alias /root/deploy/nginx-shared/staticfiles;
            expires 365d;
        }

        location / {
          proxy_pass http://app_server/;
          proxy_set_header Host $host;
          proxy_set_header X-Forwarded-Host $server_name;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header        X-Forwarded-Proto $scheme;
          add_header              Front-End-Https   on;
          # we don't want nginx trying to do something clever with
          # redirects, we set the Host: header above already.
          proxy_redirect off;
          # They default to 60s. Increase to avoid WORKER TIMEOUT in web container
          proxy_connect_timeout 60s;
          proxy_read_timeout 60s;
        }
}

**Comment by fmrsabino** [comment]
Hey @masayil 

Thanks for the issue. This seems however to be a configuration issue on Nginx which is not related with this project.

We have an nginx service on docker-compose just as an example. For production needs a reverse-proxy should be configured if required. But that configuration is not up to us.
