### ISSUE TITLE
500 Error on unsanitized URL query params 

### ISSUE THREAD

**Issue by hectorgomezv** [safe-global/safe-config-service#697]
**Describe the bug**
Error response with 500 Internal server Error is returned to the clients when a unsanitized URL query param is sent to the service.

**To Reproduce**
- Check: https://safe-config.safe.global/api/v1/safe-apps/?url=%00

**Expected behavior**
URL input is sanitized beforehand.

**Environment**
 - Staging & production
 - All chains

**Comment by Uxio0** [comment]
I provided more info on the PR

**Comment by fmrsabino** [comment]
> URL input is sanitized and therefore a 404 is returned to the client.

Just a small note but the expected behaviour should not be `404` since this acts as a filter on a collection – we were already returning an empty collection in those cases

**Comment by hectorgomezv** [comment]
> > URL input is sanitized and therefore a 404 is returned to the client.
> 
> Just a small note but the expected behaviour should not be `404` since this acts as a filter on a collection – we were already returning an empty collection in those cases

Thanks, description updated 👍🏻
