### ISSUE TITLE
Fail to run `docker compose up -d db` according to README

### ISSUE THREAD

**Issue by gzliudan** [safe-global/safe-config-service#728]
**Describe the bug**
Fail to run `docker compose up -d db`. Shall I set enviorment DOCKER_NGINX_VOLUME_ROOT ? If yes, which value should it be?

**To Reproduce**

- run `docker compose up -d db` in the shell according to https://github.com/safe-global/safe-config-service#2-launch-the-postgres-database-image

**Expected behavior**
The command should not report any error message.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 2.41.0

**Additional context**
Error messages:
```text
WARN[0000] The "NGINX_HOST_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOCKER_NGINX_VOLUME_ROOT" variable is not set. Defaulting to a blank string.
WARN[0000] The "POSTGRES_PORT" variable is not set. Defaulting to a blank string.
WARN[0000] The "DOCKER_NGINX_VOLUME_ROOT" variable is not set. Defaulting to a blank string.
1 error(s) decoding:

* error decoding 'Volumes[1]': invalid spec: nginx-shared:: empty section between colons
```

**Comment by fmrsabino** [comment]
Thanks for reporting this issue.

We should not assume that the environment variables are indeed set. Even though they can be set via the `.env` file we want to provide a quick way where you can start the service with some sensible development defaults without having to tweak your local environment.

My proposal is under: https://github.com/safe-global/safe-config-service/pull/730

However your solution in https://github.com/safe-global/safe-config-service/pull/729 should work just fine. But our goal is to streamline the startup of these services (without changing the local environment)

**Comment by gzliudan** [comment]
Your solution https://github.com/safe-global/safe-config-service/pull/730 is better.

**Comment by fmrsabino** [comment]
Thank you for the contribution! @gzliudan
