### ISSUE TITLE
Store social media links for Safe Apps

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-config-service#739]
**Is your feature request related to a problem? Please describe.**
As a part of improving the [discoverability of Safe Apps](https://www.notion.so/gnosis-safe/Discoverability-of-Safe-Apps-ae7f9a4066d64a45ac038397f1703511), we want to have links to app's websites and social media platofrms.

**Provide references to the feature you are implementing that requires this change**
- [Problem statement](https://www.notion.so/gnosis-safe/Discoverability-of-Safe-Apps-ae7f9a4066d64a45ac038397f1703511)
- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2231%3A64547&t=IgOfrzNdC4yo5nFc-3)

**Describe the solution you'd like**
The safe apps model would have an array of social links with an URL and link type

**Describe alternatives you've considered**
Fetching them from coingecko/coinmarketcap/etc

**Additional context**
I'm willing to work on this problem myself :)

**Comment by johannesmoormann** [comment]
Please wait for prioritization meeting results before committing to the implementation.

**Comment by fmrsabino** [comment]
> The safe apps model would have an array of social links with an URL and link type

Do we want to target specific social links or do we want to have a generic collection of social media links? Do they have an icon? (I can't open the Figma link)

> The safe apps model would have an array of features similar to features on chain model

Can you give an example of what these features represent?

---

I would consider splitting this ticket into two. I don't think they are related to each other right? One for media links and the other for features.

**Comment by mikhailxyz** [comment]
> Do we want to target specific social links or do we want to have a generic collection of social media links? Do they have an icon? (I can't open the Figma link)

<img width="737" alt="Screenshot 2023-01-12 at 12 19 38" src="https://user-images.githubusercontent.com/16622558/212053982-b6ea8c61-acde-40af-bab4-edd8696e45d0.png">

This is how it looks. We want to link application's social media platform such as twitter, github, discord, landing page, etc

**Comment by mikhailxyz** [comment]
> Can you give an example of what these features represent?

Right now the only feature the app can enable is batched transactions. Perhaps it can be a simple boolean field on the apps model, but i think an array with features is a more long-term solution 

> I would consider splitting this ticket into two. I don't think they are related to each other right? One for media links and the other for features.

Correct, they're unrelated but since they both seemed small and straightforward I included both here. I can create a separate ticket for features if you say it's better

**Comment by fmrsabino** [comment]
> > Do we want to target specific social links or do we want to have a generic collection of social media links? Do they have an icon? (I can't open the Figma link)
> 
> <img alt="Screenshot 2023-01-12 at 12 19 38" width="250" src="https://user-images.githubusercontent.com/16622558/212053982-b6ea8c61-acde-40af-bab4-edd8696e45d0.png">
> 
> This is how it looks. We want to link application's social media platform such as twitter, github, discord, landing page, etc

Given the image here it seems like the following:

- Each app only has one website. I would just add a single field for this one on the `SafeApp` level
- Each app can have multiple social media links
  * Here we can either have the resource of the each social media on the Safe Config Service OR
  * Have a type of social media eg.: `DISCORD | TWITTER | GITHUB` etc..
  * A new table with all the social media links (I think having this tied to the SafeApp table can be more confusing but we can also consider this option).
    - This new "social links" table would be something like `SAFE APP ID | SOCIAL MEDIA TYPE | SOCIAL MEDIA URL`

**Comment by fmrsabino** [comment]
> > Can you give an example of what these features represent?
> 
> Right now the only feature an app can enable is batched transactions. Perhaps it can be a simple boolean field on the apps model, but i think an array with features is a more long-term solution
> 

I think we can work on the long-term solution now because it seems easy enough to accomplish this and we don't need to migrate this data to a new format later on. The feature itself looks like it's going to be used for different types so I'd assume that from the get go.

> > I would consider splitting this ticket into two. I don't think they are related to each other right? One for media links and the other for features.
> 
> Correct, they're unrelated but since they both seemed small and straightforward I included both here. I can create a separate ticket for features if you say it's better

I think it makes it easier to track the development of each one (since one can happen without the other technically) 😉

**Comment by mikhailxyz** [comment]
> > > Can you give an example of what these features represent?
> > 
> > 
> > Right now the only feature an app can enable is batched transactions. Perhaps it can be a simple boolean field on the apps model, but i think an array with features is a more long-term solution
> 
> I think we can work on the long-term solution now because it seems easy enough to accomplish this and we don't need to migrate this data to a new format later on. The feature itself looks like it's going to be used for different types so I'd assume that from the get go.
> 
> > > I would consider splitting this ticket into two. I don't think they are related to each other right? One for media links and the other for features.
> > 
> > 
> > Correct, they're unrelated but since they both seemed small and straightforward I included both here. I can create a separate ticket for features if you say it's better
> 
> I think it makes it easier to track the development of each one (since one can happen without the other technically) 😉

Features are now tracked here https://github.com/safe-global/safe-config-service/issues/755

**Comment by mikhailxyz** [comment]
> > > Do we want to target specific social links or do we want to have a generic collection of social media links? Do they have an icon? (I can't open the Figma link)
> > 
> > 
> > <img alt="Screenshot 2023-01-12 at 12 19 38" width="250" src="https://user-images.githubusercontent.com/16622558/212053982-b6ea8c61-acde-40af-bab4-edd8696e45d0.png">
> > This is how it looks. We want to link application's social media platform such as twitter, github, discord, landing page, etc
> 
> Given the image here it seems like the following:
> 
> * Each app only has one website. I would just add a single field for this one on the `SafeApp` level
> * Each app can have multiple social media links
>   
>   * Here we can either have the resource of the each social media on the Safe Config Service OR
>   * Have a type of social media eg.: `DISCORD | TWITTER | GITHUB` etc..
>   * A new table with all the social media links (I think having this tied to the SafeApp table can be more confusing but we can also consider this option).
>     
>     * This new "social links" table would be something like `SAFE APP ID | SOCIAL MEDIA TYPE | SOCIAL MEDIA URL`
> 
> Wdyt?

Sounds good to me. This is a similar approach to what I've been envisioning: https://stackoverflow.com/questions/48755827/how-to-store-social-usernames-links-in-django

**Comment by fmrsabino** [comment]
@mikhailxyz This can be closed right (as the feature was merged)?

**Comment by mikhailxyz** [comment]
yes, thanks for the reminder @fmrsabino
