### ISSUE TITLE
Store Safe App features

### ISSUE THREAD

**Issue by mikhailxyz** [safe-global/safe-config-service#755]
**Is your feature request related to a problem? Please describe.**
As a part of improving the [discoverability of Safe Apps](https://www.notion.so/gnosis-safe/Discoverability-of-Safe-Apps-ae7f9a4066d64a45ac038397f1703511), we want to highlight applications that have safe specific features such as batched transactions

**Provide references to the feature you are implementing that requires this change**
- [Problem statement](https://www.notion.so/gnosis-safe/Discoverability-of-Safe-Apps-ae7f9a4066d64a45ac038397f1703511)
- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=2231%3A64547&t=IgOfrzNdC4yo5nFc-3)

**Describe the solution you'd like**
The safe apps model would have an array of features similar to features on the chain model

**Describe alternatives you've considered**
At the moment, the app can only enable a single safe-specific feature (batched transactions) and we considered adding a simple boolean field but an array of features sounds like a more long-term oriented solution

**Additional context**
I'm willing to work on this problem myself :)

**Comment by fmrsabino** [comment]
@mikhailxyz This can be closed right (as the feature was merged)?

**Comment by mikhailxyz** [comment]
yes, thanks for the reminder @fmrsabino
